"use strict";
const thisIsAString = "Yeah";
const thisIsANumber = 30;
let thisIsNotUsed;
thisIsNotUsed = 5;
// const newObj = new Object();
// const newMap = new Map();
// const mySet = new set();
// const myArr = new Array();
console.log(`${thisIsAString} the number is ${thisIsANumber}. Let\'s not forget ${thisIsNotUsed}`);
